path = "clipboard.md"
max_loc = 1500
poll_interval = 25
cache_capacity = 100
history_capacity = 45
history_width = 80
watcher_interval = 10
filter = []
invalid_patterns = []

[[regex]]
pattern = '\n+\s?'
rep = ""

[[bindings]]
key = 1
placement = "before"
flush = false
content = "Bound to key 1\n\n"

[[bindings]]
key = 2
placement = "after"
flush = true
content = "Bound to key 2\n\n"
